"""Secrets Security and Cryptographic Asset Intelligence public API (EA-0032)."""

from aqelyn.secrets.engine import SecretsIntelligenceEngine
from aqelyn.secrets.exposure import CryptoKnownSurfaceSource
from aqelyn.secrets.lifecycle import CertificateAuthenticityVerifier
from aqelyn.secrets.memory import InMemoryCryptoStore
from aqelyn.secrets.models import (
    VALID_ASSESSMENT_STATUSES,
    VALID_CRYPTO_ASSET_KINDS,
    VALID_KEY_USAGES,
    VALID_LIFECYCLE_STATUSES,
    VALID_SECRET_KINDS,
    VALID_SECRET_LOCATION_KINDS,
    AssessmentStatus,
    AuthenticityCheck,
    CertificateAsset,
    CertificateClaim,
    CertificateDescriptor,
    CredentialGovernanceScore,
    CryptoAssessment,
    CryptoAsset,
    CryptoAssetKind,
    CryptoClaim,
    CryptoClaimConflict,
    CryptoClaimField,
    CryptoConfig,
    CryptoConflictCandidate,
    CryptoExposureStatus,
    CryptographicExposure,
    CryptographicKey,
    CryptographicKeyDescriptor,
    CryptoQuery,
    CryptoScope,
    GovernanceFactor,
    GovernanceFactorStatus,
    GovernanceScoringStatus,
    KeyClaim,
    KeyUsage,
    Lifecycle,
    LifecycleStatus,
    SecretAsset,
    SecretClaim,
    SecretKind,
    SecretLocation,
    SecretLocationKind,
    SecretScanDescriptor,
    StorageLocationKind,
    StorageSafetyClassification,
    StorageSafetyStatus,
)
from aqelyn.secrets.postgres import PostgresCryptoStore
from aqelyn.secrets.scoring import (
    ComposedCredentialGovernance,
    compose_credential_governance,
    governance_operation_registry,
    governance_score_result,
    validate_replayable_governance_score,
)
from aqelyn.secrets.service import (
    CRYPTO_EVENTS,
    SecretsIntelligenceService,
    register_crypto_events,
)
from aqelyn.secrets.storage import classify_storage_safety
from aqelyn.secrets.store import CryptoStore

__all__ = [
    "CRYPTO_EVENTS",
    "VALID_ASSESSMENT_STATUSES",
    "VALID_CRYPTO_ASSET_KINDS",
    "VALID_KEY_USAGES",
    "VALID_LIFECYCLE_STATUSES",
    "VALID_SECRET_KINDS",
    "VALID_SECRET_LOCATION_KINDS",
    "AssessmentStatus",
    "AuthenticityCheck",
    "CertificateAsset",
    "CertificateAuthenticityVerifier",
    "CertificateClaim",
    "CertificateDescriptor",
    "ComposedCredentialGovernance",
    "CredentialGovernanceScore",
    "CryptoAssessment",
    "CryptoAsset",
    "CryptoAssetKind",
    "CryptoClaim",
    "CryptoClaimConflict",
    "CryptoClaimField",
    "CryptoConfig",
    "CryptoConflictCandidate",
    "CryptoExposureStatus",
    "CryptoKnownSurfaceSource",
    "CryptoQuery",
    "CryptoScope",
    "CryptoStore",
    "CryptographicExposure",
    "CryptographicKey",
    "CryptographicKeyDescriptor",
    "GovernanceFactor",
    "GovernanceFactorStatus",
    "GovernanceScoringStatus",
    "InMemoryCryptoStore",
    "KeyClaim",
    "KeyUsage",
    "Lifecycle",
    "LifecycleStatus",
    "PostgresCryptoStore",
    "SecretAsset",
    "SecretClaim",
    "SecretKind",
    "SecretLocation",
    "SecretLocationKind",
    "SecretScanDescriptor",
    "SecretsIntelligenceEngine",
    "SecretsIntelligenceService",
    "StorageLocationKind",
    "StorageSafetyClassification",
    "StorageSafetyStatus",
    "classify_storage_safety",
    "compose_credential_governance",
    "governance_operation_registry",
    "governance_score_result",
    "register_crypto_events",
    "validate_replayable_governance_score",
]
