"""Predictive Analytics & Forecasting Engine (EA-0021)."""

from aqelyn.forecast.engine import (
    EvidenceLookup,
    ForecastingEngine,
    MetricHistorySource,
    TrustAssessor,
    statement_from_derivation,
    validate_forecast_subject_ref,
)
from aqelyn.forecast.memory import InMemoryForecastStore, InMemoryPredictionModelStore
from aqelyn.forecast.methods import (
    MethodRegistry,
    MethodResult,
    PureForecastFn,
    default_method_registry,
    holt_winters,
    linear_trend,
    moving_average,
    rate_extrapolation,
    seasonal_naive,
)
from aqelyn.forecast.models import (
    VALID_BASIS_KINDS,
    VALID_FORECAST_SUBJECT_PREFIXES,
    VALID_METHODS,
    VALID_TREND_DIRECTIONS,
    AccuracyRecord,
    BasisKind,
    BasisRef,
    Forecast,
    ForecastConfig,
    ForecastPublication,
    Interval,
    Method,
    Outcome,
    PredictionModel,
    Scenario,
    TrendDirection,
    TrendRecord,
)
from aqelyn.forecast.postgres import PostgresForecastStore, PostgresPredictionModelStore
from aqelyn.forecast.scenario import (
    scenario_operation_registry,
    scenario_result,
    simulate_scenario,
)
from aqelyn.forecast.scoring import (
    ActualValueSource,
    EvidenceRecorder,
    accuracy_records,
    publish_forecasts,
    scored_outcome,
    unscoreable_outcome,
)
from aqelyn.forecast.store import (
    ForecastStore,
    PredictionModelStore,
    forecast_operation_registry,
    validate_replayable_forecast,
)
from aqelyn.forecast.trend import MetricObservation, build_trend_record

__all__ = [
    "VALID_BASIS_KINDS",
    "VALID_FORECAST_SUBJECT_PREFIXES",
    "VALID_METHODS",
    "VALID_TREND_DIRECTIONS",
    "AccuracyRecord",
    "ActualValueSource",
    "BasisKind",
    "BasisRef",
    "EvidenceLookup",
    "EvidenceRecorder",
    "Forecast",
    "ForecastConfig",
    "ForecastPublication",
    "ForecastStore",
    "ForecastingEngine",
    "InMemoryForecastStore",
    "InMemoryPredictionModelStore",
    "Interval",
    "Method",
    "MethodRegistry",
    "MethodResult",
    "MetricHistorySource",
    "MetricObservation",
    "Outcome",
    "PostgresForecastStore",
    "PostgresPredictionModelStore",
    "PredictionModel",
    "PredictionModelStore",
    "PureForecastFn",
    "Scenario",
    "TrendDirection",
    "TrendRecord",
    "TrustAssessor",
    "accuracy_records",
    "build_trend_record",
    "default_method_registry",
    "forecast_operation_registry",
    "holt_winters",
    "linear_trend",
    "moving_average",
    "publish_forecasts",
    "rate_extrapolation",
    "scenario_operation_registry",
    "scenario_result",
    "scored_outcome",
    "seasonal_naive",
    "simulate_scenario",
    "statement_from_derivation",
    "unscoreable_outcome",
    "validate_forecast_subject_ref",
    "validate_replayable_forecast",
]
