"""Predictive Analytics & Forecasting Engine (EA-0021)."""

from aqelyn.forecast.methods import (
    MethodRegistry,
    MethodResult,
    PureForecastFn,
    default_method_registry,
    holt_winters,
    linear_trend,
    moving_average,
    rate_extrapolation,
    seasonal_naive,
)
from aqelyn.forecast.models import (
    VALID_BASIS_KINDS,
    VALID_METHODS,
    VALID_TREND_DIRECTIONS,
    AccuracyRecord,
    BasisKind,
    BasisRef,
    Forecast,
    ForecastConfig,
    Interval,
    Method,
    Outcome,
    PredictionModel,
    Scenario,
    TrendDirection,
    TrendRecord,
)

__all__ = [
    "VALID_BASIS_KINDS",
    "VALID_METHODS",
    "VALID_TREND_DIRECTIONS",
    "AccuracyRecord",
    "BasisKind",
    "BasisRef",
    "Forecast",
    "ForecastConfig",
    "Interval",
    "Method",
    "MethodRegistry",
    "MethodResult",
    "Outcome",
    "PredictionModel",
    "PureForecastFn",
    "Scenario",
    "TrendDirection",
    "TrendRecord",
    "default_method_registry",
    "holt_winters",
    "linear_trend",
    "moving_average",
    "rate_extrapolation",
    "seasonal_naive",
]
