"""Executive Intelligence & Strategic Reporting Engine (EA-0022)."""

from aqelyn.executive.definitions import KPIDefinitionStore
from aqelyn.executive.exceptions import MaterialExceptionSource, collect_material_exceptions
from aqelyn.executive.kpi import (
    DrillDownRecord,
    ExecutiveKPIEngine,
    KPIValueSource,
    OwnerMetric,
    compute_kpi,
    drill_down,
    kpi_operation_registry,
    kpi_result,
)
from aqelyn.executive.memory import InMemoryKPIDefinitionStore, InMemoryReportStore
from aqelyn.executive.models import (
    VALID_BANDS,
    VALID_COMBINATORS,
    VALID_INPUT_METRICS,
    VALID_REPORT_SECTIONS,
    VALID_SOURCE_KINDS,
    ApprovalStatus,
    Dashboard,
    ExceptionItem,
    ExecutiveBriefing,
    ExecutiveConfig,
    ExecutiveReport,
    Figure,
    KPIDefinition,
    KPIInput,
    KPIRecord,
    ReportConfig,
    ReportExclude,
    ReportSection,
    SourceKind,
    SourceRef,
)
from aqelyn.executive.postgres import PostgresKPIDefinitionStore, PostgresReportStore
from aqelyn.executive.report import (
    EvidenceRecorder,
    ExecutiveReportEngine,
    SectionFigureSource,
    assemble_report,
    content_hash_for_report,
    forecast_summary_figure,
    issue_report,
)
from aqelyn.executive.store import ReportStore

__all__ = [
    "VALID_BANDS",
    "VALID_COMBINATORS",
    "VALID_INPUT_METRICS",
    "VALID_REPORT_SECTIONS",
    "VALID_SOURCE_KINDS",
    "ApprovalStatus",
    "Dashboard",
    "DrillDownRecord",
    "EvidenceRecorder",
    "ExceptionItem",
    "ExecutiveBriefing",
    "ExecutiveConfig",
    "ExecutiveKPIEngine",
    "ExecutiveReport",
    "ExecutiveReportEngine",
    "Figure",
    "InMemoryKPIDefinitionStore",
    "InMemoryReportStore",
    "KPIDefinition",
    "KPIDefinitionStore",
    "KPIInput",
    "KPIRecord",
    "KPIValueSource",
    "MaterialExceptionSource",
    "OwnerMetric",
    "PostgresKPIDefinitionStore",
    "PostgresReportStore",
    "ReportConfig",
    "ReportExclude",
    "ReportSection",
    "ReportStore",
    "SectionFigureSource",
    "SourceKind",
    "SourceRef",
    "assemble_report",
    "collect_material_exceptions",
    "compute_kpi",
    "content_hash_for_report",
    "drill_down",
    "forecast_summary_figure",
    "issue_report",
    "kpi_operation_registry",
    "kpi_result",
]
