"""Threat Exposure & Attack Surface Management Engine (EA-0023)."""

from aqelyn.exposure.engine import (
    ExposureEvidenceLookup,
    ExposureMissionProvider,
    ExposurePathGraph,
    ExposureTrendProvider,
    ExposureTrustProvider,
    IdentityExposureProvider,
    KnownDataExposureEngine,
    KnownSurfaceRecord,
    KnownSurfaceSource,
    StaticKnownSurfaceSource,
    validate_replayable_exposure,
)
from aqelyn.exposure.memory import InMemoryExposureStore
from aqelyn.exposure.models import (
    ACTIVE_SCAN_CAPABILITY,
    VALID_ASSET_KINDS,
    VALID_BASIS_KINDS,
    VALID_EXPOSURE_LEVELS,
    VALID_EXPOSURE_STATUS,
    VALID_REACHABILITY,
    AssetKind,
    AssetRef,
    AttackSurfaceAsset,
    ExposureBasis,
    ExposureBasisKind,
    ExposureConfig,
    ExposureLevel,
    ExposureRecord,
    ExposureStatus,
    Reachability,
    ReachablePath,
    active_reachability_action_spec,
    refuse_active_reachability_collection,
)
from aqelyn.exposure.postgres import PostgresExposureStore
from aqelyn.exposure.service import (
    EXPOSURE_EVENTS,
    ExposureManagementService,
    register_exposure_events,
)
from aqelyn.exposure.store import ExposureStore

__all__ = [
    "ACTIVE_SCAN_CAPABILITY",
    "EXPOSURE_EVENTS",
    "VALID_ASSET_KINDS",
    "VALID_BASIS_KINDS",
    "VALID_EXPOSURE_LEVELS",
    "VALID_EXPOSURE_STATUS",
    "VALID_REACHABILITY",
    "AssetKind",
    "AssetRef",
    "AttackSurfaceAsset",
    "ExposureBasis",
    "ExposureBasisKind",
    "ExposureConfig",
    "ExposureEvidenceLookup",
    "ExposureLevel",
    "ExposureManagementService",
    "ExposureMissionProvider",
    "ExposurePathGraph",
    "ExposureRecord",
    "ExposureStatus",
    "ExposureStore",
    "ExposureTrendProvider",
    "ExposureTrustProvider",
    "IdentityExposureProvider",
    "InMemoryExposureStore",
    "KnownDataExposureEngine",
    "KnownSurfaceRecord",
    "KnownSurfaceSource",
    "PostgresExposureStore",
    "Reachability",
    "ReachablePath",
    "StaticKnownSurfaceSource",
    "active_reachability_action_spec",
    "refuse_active_reachability_collection",
    "register_exposure_events",
    "validate_replayable_exposure",
]
