"""AI Decision Intelligence Engine (EA-0020)."""

from aqelyn.decision.derive import (
    build_derivation,
    explain,
    replay,
    validate_replayable_recommendation,
)
from aqelyn.decision.memory import InMemoryModelVersionStore, InMemoryRecommendationStore
from aqelyn.decision.models import (
    VALID_CLAIM_KINDS,
    VALID_DECISIONS,
    ClaimKind,
    ClaimRef,
    DecisionConfig,
    DecisionOutcome,
    DecisionRecord,
    Derivation,
    DerivationStep,
    LearningRecord,
    ModelVersion,
    Recommendation,
    SimilarityHit,
)
from aqelyn.decision.operations import (
    DEFAULT_OPERATION_NAMES,
    JsonMap,
    JsonMapping,
    OperationRegistry,
    PureOp,
    default_operation_registry,
    filter_items,
    mission_weight,
    rank,
    select_claims,
    similarity,
    threshold,
    weigh,
)
from aqelyn.decision.postgres import PostgresModelVersionStore, PostgresRecommendationStore
from aqelyn.decision.recommend import (
    ClaimSource,
    DecisionIntelligenceEngine,
    TrustAssessor,
    WorkflowProposer,
)
from aqelyn.decision.similarity import CaseCorpus, CaseFeatures, similar_cases
from aqelyn.decision.store import ModelVersionStore, RecommendationStore

__all__ = [
    "DEFAULT_OPERATION_NAMES",
    "VALID_CLAIM_KINDS",
    "VALID_DECISIONS",
    "CaseCorpus",
    "CaseFeatures",
    "ClaimKind",
    "ClaimRef",
    "ClaimSource",
    "DecisionConfig",
    "DecisionIntelligenceEngine",
    "DecisionOutcome",
    "DecisionRecord",
    "Derivation",
    "DerivationStep",
    "InMemoryModelVersionStore",
    "InMemoryRecommendationStore",
    "JsonMap",
    "JsonMapping",
    "LearningRecord",
    "ModelVersion",
    "ModelVersionStore",
    "OperationRegistry",
    "PostgresModelVersionStore",
    "PostgresRecommendationStore",
    "PureOp",
    "Recommendation",
    "RecommendationStore",
    "SimilarityHit",
    "TrustAssessor",
    "WorkflowProposer",
    "build_derivation",
    "default_operation_registry",
    "explain",
    "filter_items",
    "mission_weight",
    "rank",
    "replay",
    "select_claims",
    "similar_cases",
    "similarity",
    "threshold",
    "validate_replayable_recommendation",
    "weigh",
]
